[[main]]
    identifier = "home"
    name = "Home"
    pre = "<i class='fa fa-heart'></i>"
    url = "/"
    weight = 1

[[main]]
    name = "Sections"
    post = ""
    pre = "<i class='fa fa-heart'></i>"
    weight = 3


[[main]]
    name = "Linux"
    url = "/categories/linux"
    parent = "Sections"


[[main]]
    name = "Social"
    post = ""
    pre = "<i class='fa fa-heart'></i>"
    weight = 4

[[main]]
    name = "YouTube"
    url = "https://www.youtube.com/channel/UC3AmvMs0DT-4dypIaVzBEbw"
    hrefTargetBlank = true
    parent = "Social"
